### ISSUE TITLE
spec 0.2.1 - add deployment attribute to get-sli

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/spec#72]
From discussion in https://github.com/keptn/spec/issues/68 

Goal: We need to add a `deployment` field to `get-sli.triggered`

# Tasks
- [x] Add `deployment` to `get-sli.triggered` in go-utils
- [x] Merge go-utils in keptn core
- [x] Generate spec using CLI `keptn generate-spec` and create a PR on the keptn/spec repo
